In [111]:
import pandas as pd

In [112]:
df = pd.read_csv("finance_clean_kpis.csv")

In [113]:
df

,company,year,total_revenue,net_income,total_assets,total_liabilities,cash_flow_from_operating_activities,Revenue Growth (%),Net Income Growth (%),Debt ratio,Profit Margin (%),Operating CF margin (%),Asset Growth (%)
0,Apple,2023,383285.0,96995.0,352583.0,290437.0,110543.0,NaN,NaN,0.823741,25.306234,28.840941,NaN
1,Apple,2024,391035.0,93736.0,364980.0,308030.0,118254.0,2.021994,-3.359967,0.843964,23.971256,30.241283,3.516052
2,Apple,2025,416161.0,112010.0,359241.0,285508.0,111482.0,6.425512,19.495178,0.794753,26.915064,26.788190,-1.572415
3,Microsoft,2023,211915.0,72361.0,411976.0,205753.0,87582.0,NaN,NaN,0.499430,34.146238,41.328835,NaN
4,Microsoft,2024,245122.0,88136.0,512163.0,243686.0,118548.0,15.669962,21.800417,0.475798,35.955973,48.362856,24.318650
5,Microsoft,2025,281724.0,101832.0,619003.0,275524.0,136162.0,14.932156,15.539621,0.445109,36.146015,48.331701,20.860546
6,Tesla,2023,96773.0,14974.0,106618.0,43009.0,13256.0,NaN,NaN,0.403393,15.473324,13.698036,NaN
7,Tesla,2024,97690.0,7153.0,122070.0,48390.0,14923.0,0.947578,-52.230533,0.396412,7.322141,15.275873,14.492862
8,Tesla,2025,94827.0,3855.0,137806.0,54941.0,14747.0,-2.930699,-46.106529,0.398684,4.065298,15.551478,12.890964

In [114]:
# now what could happen is you may write question Debt Ratio and in your df it is debt ratio..
# so remove such name cases error:

df.columns = (
    df.columns
        .str.strip()        # remove spaces at start/end
        .str.lower()        # convert to lowercase
        .str.replace(" ", "_")   # replace spaces with _
        .str.replace(r"[^\w]", "", regex=True)  # remove special chars
)

In [115]:
df

,company,year,total_revenue,net_income,total_assets,total_liabilities,cash_flow_from_operating_activities,revenue_growth_,net_income_growth_,debt_ratio,profit_margin_,operating_cf_margin_,asset_growth_
0,Apple,2023,383285.0,96995.0,352583.0,290437.0,110543.0,NaN,NaN,0.823741,25.306234,28.840941,NaN
1,Apple,2024,391035.0,93736.0,364980.0,308030.0,118254.0,2.021994,-3.359967,0.843964,23.971256,30.241283,3.516052
2,Apple,2025,416161.0,112010.0,359241.0,285508.0,111482.0,6.425512,19.495178,0.794753,26.915064,26.788190,-1.572415
3,Microsoft,2023,211915.0,72361.0,411976.0,205753.0,87582.0,NaN,NaN,0.499430,34.146238,41.328835,NaN
4,Microsoft,2024,245122.0,88136.0,512163.0,243686.0,118548.0,15.669962,21.800417,0.475798,35.955973,48.362856,24.318650
5,Microsoft,2025,281724.0,101832.0,619003.0,275524.0,136162.0,14.932156,15.539621,0.445109,36.146015,48.331701,20.860546
6,Tesla,2023,96773.0,14974.0,106618.0,43009.0,13256.0,NaN,NaN,0.403393,15.473324,13.698036,NaN
7,Tesla,2024,97690.0,7153.0,122070.0,48390.0,14923.0,0.947578,-52.230533,0.396412,7.322141,15.275873,14.492862
8,Tesla,2025,94827.0,3855.0,137806.0,54941.0,14747.0,-2.930699,-46.106529,0.398684,4.065298,15.551478,12.890964

In [116]:
# if you see closely -> its revenue_growth_ and no (%) -> not looking good
# Special characters like '%' cannot be used in variable names, which is why it's being replaced with an underscore.


df.rename(columns={'revenue_growth_': 'revenue_growth_(%)'}, inplace=True)
df.rename(columns={'net_income_growth_': 'net_income_growth_(%)'}, inplace=True)
df.rename(columns={'profit_margin_': 'profit_margin_(%)'}, inplace=True)
df.rename(columns={'operating_cf_margin_': 'operating_cf_margin_(%)'}, inplace=True)
df.rename(columns={'asset_growth_': 'asset_growth_(%)'}, inplace=True)


# The `inplace=True` parameter is used in many pandas methods to modify the DataFrame directly without creating a new copy. 
### What `inplace=True` does:
# 1. **Modifies the original object**: Changes are applied directly to the original DataFrame
# 2. **Saves memory**: Avoids creating a new copy of potentially large DataFrames
# 3. **No need for reassignment**: You don't need to write `df = df.rename(...)`

In [117]:
df

,company,year,total_revenue,net_income,total_assets,total_liabilities,cash_flow_from_operating_activities,revenue_growth_(%),net_income_growth_(%),debt_ratio,profit_margin_(%),operating_cf_margin_(%),asset_growth_(%)
0,Apple,2023,383285.0,96995.0,352583.0,290437.0,110543.0,NaN,NaN,0.823741,25.306234,28.840941,NaN
1,Apple,2024,391035.0,93736.0,364980.0,308030.0,118254.0,2.021994,-3.359967,0.843964,23.971256,30.241283,3.516052
2,Apple,2025,416161.0,112010.0,359241.0,285508.0,111482.0,6.425512,19.495178,0.794753,26.915064,26.788190,-1.572415
3,Microsoft,2023,211915.0,72361.0,411976.0,205753.0,87582.0,NaN,NaN,0.499430,34.146238,41.328835,NaN
4,Microsoft,2024,245122.0,88136.0,512163.0,243686.0,118548.0,15.669962,21.800417,0.475798,35.955973,48.362856,24.318650
5,Microsoft,2025,281724.0,101832.0,619003.0,275524.0,136162.0,14.932156,15.539621,0.445109,36.146015,48.331701,20.860546
6,Tesla,2023,96773.0,14974.0,106618.0,43009.0,13256.0,NaN,NaN,0.403393,15.473324,13.698036,NaN
7,Tesla,2024,97690.0,7153.0,122070.0,48390.0,14923.0,0.947578,-52.230533,0.396412,7.322141,15.275873,14.492862
8,Tesla,2025,94827.0,3855.0,137806.0,54941.0,14747.0,-2.930699,-46.106529,0.398684,4.065298,15.551478,12.890964

# Chatbot Basic Structure based Rule based Logic
# if else and elif used

In [118]:
def chatbot(df):

    print("\nFinanceBot Ready!")
    print()
    print("NOTE: Type 'exit' anytime to quit.\n")

    while True:

        print("\nAvailable Questions:")
        print("1. Show revenue for latest year")
        print("2. Show net income for latest year")
        print("3. Company with highest revenue")
        print("4. Company with highest net income")
        print("5. Show revenue growth by company")
        print("6. Show profit margin")
        print("7. Show debt ratio")
        print("8. Show total assets for latest year")
        print("9. Company with lowest debt ratio")
        print("10. Compare operating cash flow")

        user = input("\nEnter question number: ")

        if user.lower() == "exit":
            print("FinanceBot: Goodbye!")
            break

        latest_year = df["year"].max()
        latest = df[df["year"] == latest_year]

        # Q1 Revenue
        if user == "1":
            print(f"\nRevenue in {latest_year}:")
            print(latest[["company", "total_revenue"]])

        # Q2 Net income
        elif user == "2":
            print(f"\nNet Income in {latest_year}:")
            print(latest[["company", "net_income"]])

        # Q3 Highest revenue
        elif user == "3":
            top = latest.loc[latest["total_revenue"].idxmax()]
            print(f"\nHighest revenue company: {top['company']}")

        # Q4 Highest net income
        elif user == "4":
            top = latest.loc[latest["net_income"].idxmax()]
            print(f"\nHighest net income company: {top['company']}")

        # Q5 Revenue growth
        elif user == "5":
            print("\nRevenue Growth:")
            print(df[["company", "year", "revenue_growth_(%)"]])

        # Q6 Profit margin
        elif user == "6":
            print("\nProfit Margin (%):")
            print(df[["company", "year", "profit_margin_(%)"]])

        # Q7 Debt ratio
        elif user == "7":
            print("\nDebt Ratio:")
            print(df[["company", "year", "debt_ratio"]])

        # Q8 Assets
        elif user == "8":
            print(f"\nTotal Assets in {latest_year}:")
            print(latest[["company", "total_assets"]])

        # Q9 Lowest debt ratio
        elif user == "9":
            safest = latest.loc[latest["debt_ratio"].idxmin()]
            print(f"\nLowest debt ratio company: {safest['company']}")

        # Q10 Cash flow comparison
        elif user == "10":
            print("\nOperating Cash Flow:")
            print(latest[["company", "cash_flow_from_operating_activities"]])

        else:
            print("Sorry, I can only provide information on predefined queries.")

In [119]:
df

,company,year,total_revenue,net_income,total_assets,total_liabilities,cash_flow_from_operating_activities,revenue_growth_(%),net_income_growth_(%),debt_ratio,profit_margin_(%),operating_cf_margin_(%),asset_growth_(%)
0,Apple,2023,383285.0,96995.0,352583.0,290437.0,110543.0,NaN,NaN,0.823741,25.306234,28.840941,NaN
1,Apple,2024,391035.0,93736.0,364980.0,308030.0,118254.0,2.021994,-3.359967,0.843964,23.971256,30.241283,3.516052
2,Apple,2025,416161.0,112010.0,359241.0,285508.0,111482.0,6.425512,19.495178,0.794753,26.915064,26.788190,-1.572415
3,Microsoft,2023,211915.0,72361.0,411976.0,205753.0,87582.0,NaN,NaN,0.499430,34.146238,41.328835,NaN
4,Microsoft,2024,245122.0,88136.0,512163.0,243686.0,118548.0,15.669962,21.800417,0.475798,35.955973,48.362856,24.318650
5,Microsoft,2025,281724.0,101832.0,619003.0,275524.0,136162.0,14.932156,15.539621,0.445109,36.146015,48.331701,20.860546
6,Tesla,2023,96773.0,14974.0,106618.0,43009.0,13256.0,NaN,NaN,0.403393,15.473324,13.698036,NaN
7,Tesla,2024,97690.0,7153.0,122070.0,48390.0,14923.0,0.947578,-52.230533,0.396412,7.322141,15.275873,14.492862
8,Tesla,2025,94827.0,3855.0,137806.0,54941.0,14747.0,-2.930699,-46.106529,0.398684,4.065298,15.551478,12.890964

In [120]:
chatbot(df)

FinanceBot Ready!

NOTE: Type 'exit' anytime to quit.


Available Questions:
1. Show revenue for latest year
2. Show net income for latest year
3. Company with highest revenue
4. Company with highest net income
5. Show revenue growth by company
6. Show profit margin
7. Show debt ratio
8. Show total assets for latest year
9. Company with lowest debt ratio
10. Compare operating cash flow

Enter question number:  exit

FinanceBot: Goodbye!

In [122]:
df.to_csv("chatbot_finalcsv_changes_recorded.csv")